version: "3.9"

volumes:
  static:
  recipe_book_media:
    external: true
  logs:
  recipe_book_db:
    external: true

services:
  db:
    container_name: recipe_book_db
    image: postgres:14.2
    volumes:
      - recipe_book_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    container_name: recipe_book_web
    restart: always
    build:
      context: .
    volumes:
      - static:/opt/static/
      - logs:/opt/logs/
      - ./:/opt/
      - recipe_book_media:/opt/media/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - APP_ENV=${APP_ENV}
    depends_on:
      - db
  nginx:
    container_name: recipe_book_nginx
    restart: always
    image: nginx:1.21.6
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - recipe_book_media:/media
      - static:/static
      - ./nginx/sites-enabled:/etc/nginx/conf.d/
