# Generated by Django 4.0.2 on 2022-02-06 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('prep_and_cooking_time', models.PositiveIntegerField(default=0, help_text='How long this recipe will take to prepare and cook (expressed in minutes)')),
                ('carb_portions', models.FloatField(default=0)),
                ('serves', models.PositiveIntegerField(default=2)),
                ('diet', models.CharField(choices=[('meat', 'meat'), ('vegetarian', 'vegetarian'), ('vegan', 'vegan')], default='vegan', max_length=11)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('last_eaten', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MethodStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.CharField(blank=True, max_length=128, null=True)),
                ('preparation', models.CharField(blank=True, max_length=128, null=True)),
                ('team', models.CharField(blank=True, max_length=128, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
