# Generated by Django 4.0.2 on 2022-02-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_location_ingredient_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.TextField(default='Get cooking!'),
        ),
        migrations.DeleteModel(
            name='MethodStep',
        ),
    ]
