# Generated by Django 4.0.4 on 2022-07-16 14:24

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):
    def forwards(apps, schema_editor):
        Recipe = apps.get_model("recipes", "Recipe")
        RecipeImage = apps.get_model("recipes", "RecipeImage")
        db_alias = schema_editor.connection.alias
        today = timezone.now().today()
        for recipe in Recipe.objects.using(db_alias).all():
            recipe_image = RecipeImage(image=recipe.image, recipe=recipe)
            recipe_image.date = recipe.last_eaten or today
            recipe_image.save()
            # need to save twice to stop auto_now_add taking over
            recipe_image.date = recipe.last_eaten or today
            recipe_image.save()

    def reverse(apps, schema_editor):
        RecipeImage = apps.get_model("recipes", "RecipeImage")
        db_alias = schema_editor.connection.alias
        RecipeImage.objects.using(db_alias).all().delete()

    dependencies = [
        ("recipes", "0007_recipeimage"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
