# Generated by Django 4.0.4 on 2022-07-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220716_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeimage',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
